### ISSUE TITLE
Chat handlers crash

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/EssentialsPlugin#100]
2016-06-15 19:16:58.5101|Error|System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIExtensions.API.ChatManager.SetupChatHandlers()
    |System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIExtensions.API.ChatManager.SetupChatHandlers()

I'm getting this error as soon as I start the server and it keeps repeating itself won't stop. It's a brand new server with the most recent versions of SESE and Essentials

**Comment by rexxar-tc** [comment]
That's a generic error that happens when the server fails to start. Unfortunately, it doesn't give us any information than "something's wrong"

**Comment by tdmike** [comment]
Should I post any logs or is there no way to fix it ?

**Comment by kirock** [comment]
Did you install NewEssentials mod on your server?

**Comment by kirock** [comment]
Had the same problem today, solved by deleting current Sandbox.sbc file(in world save) and placing new one from backup.

**Comment by tdmike** [comment]
Like I stated above, it's a brand new world, updated SESE and Essentials, I will generate a new world tomorrow.

**Comment by kirock** [comment]
Did you read the console output at the start? Probably, it will write something like that: "World '..' cant be loaded, it was created in newer version of the game"... and will continue to start without mods and world, with many many "yellow" errors.

**Comment by rexxar-tc** [comment]
The most common causes for this are when your world is corrupt in some way, or you have a non-public or dead mod in your mods list.

The server fails to load, but SESE doesn't handle that, so it keeps on going as if the server is running. Which, as you can imagine, results in a lot of bad things.
