### ISSUE TITLE
Error|System

### ISSUE THREAD

**Issue by Embolex1** [SEServerExtender/EssentialsPlugin#11]
hi,

following is for you :D 

2015-04-02 04:46:13.1413|Error|SEModAPIExtensions.API.PluginManager.LoadPlugins|System.TypeLoadException: Method 'get_Version' in type 'EssentialsPlugin.Essentials' from assembly 'Essentials, Version=1.4.0.2237, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at SEModAPIExtensions.API.PluginManager.IsOldPlugin(Assembly assembly)
   at SEModAPIExtensions.API.PluginManager.LoadPlugins(Boolean forceLoad)

![untitled](https://cloud.githubusercontent.com/assets/11764317/6956909/d01977ae-d8f4-11e4-850c-b9fa1bfdf773.jpg)

The Plugin does not load ....

**Comment by dodexahedron** [comment]
Your Essentials plugin version is not compatible with the version of SESE you are using.
Please be sure you have the latest version of each.
