### ISSUE TITLE
Information and Join Greeting do not work

### ISSUE THREAD

**Issue by eXactMatX** [SEServerExtender/EssentialsPlugin#3]
greeting item does not appear in the game
gretting message I can see in the console but not in the game

with the command / info and the topic motd comes the topic not found error even though it exists

sorry for my bad english

**Comment by Devlah** [comment]
Similar issue here as well.  I defined a join message, as well as defined an info entry. 

For example:  In essentials I defined an Information item. 
Enabled: True
IntervalSeconds:0
SubCommand: teamspeak
SubText:  Server teamspeak information.

In game, if I issue the following chat commands:
/info

The console returns:

**2015-03-29 21:53:09.7696|Info|COMMAND 144115188075855920 - 152302072485453143: /info
2015-03-29 21:53:09.7696|Info|Chat - Server: Info Error: Topic not found.
2015-03-29 21:53:09.7717|Info|Chat - Server: Type /info followed by: teamspeak for more info.  For example: '/info motd'  to view MOTD.**

If I issue a command:  /info teamspeak
I get a similar error.

I also defined a new player join message, as well as a player join message (just to test it out), and no dialog comes up on join.  I have made certain to include the client-side MOD.

I'm not sure if it's related to this at all, but I did catch some error messages during server start:

**2015-03-29 19:23:39.0177|Info|Loading plugins ...
2015-03-29 19:23:39.0177|Info|Scanning: C:\ProgramData\SpaceEngineersDedicated\CT Relaunch 3\Mods
2015-03-29 19:23:39.0347|Info|Finished loading plugins
2015-03-29 19:23:39.0387|Info|Initializing plugins ...
2015-03-29 19:23:39.0387|Info|Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\CT Relaunch 3\Mods\Essential
s\Essentials.dll - f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-03-29 19:23:39.7987|Info|Stopping all ships
2015-03-29 19:23:39.8257|Info|7 ships have been stopped
2015-03-29 19:23:39.8626|Info|Checking 0 log files for logins
2015-03-29 19:23:39.8766|Info|Completed checking logs in 0.0129976s: 2 (0) steamIds
2015-03-29 19:23:39.8816|Info|Plugin 'Dedicated Server Essentials' initialized. (Version: 1.6.0.2257  ID: f767bda5-0a8c-
4813-85fd-a5a2341778e8)
2015-03-29 19:23:39.8816|Info|Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\CT Relaunch 3\Mods\SEMotd\SE
Motd.dll - f625a48b-c28c-4ba4-a39a-637824614d0f'
SE Motd Plugin 'f625a48b-c28c-4ba4-a39a-637824614d0f' initialized!
2015-03-29 19:23:39.8816|Error|System.Reflection.TargetInvocationException: Exception has been thrown by the target of a
n invocation. ---> System.TypeLoadException: Could not load type 'SEModAPIInternal.Support.LogManager' from assembly 'SE
ModAPIInternal, Version=1.75.6.392, Culture=neutral, PublicKeyToken=null'.
   at SEMotd.SEMotd.loadXML(Boolean defaults)
   at SEMotd.SEMotd.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at SEModAPIExtensions.API.PluginManager.InitPlugin(Guid key)
2015-03-29 19:23:39.9097|Info|Finished initializing plugins
2015-03-29 19:23:40.026: Game ready... Press Ctrl+C to exit
2015-03-29 19:23:43.0677|Info|Finished loading WorldManager
2015-03-29 21:35:26.8936|Error|System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.SectorObjectManager.InternalAddEntity()**

I haven't seen any updates for SEmotd, I'm going to try running without it to see if it's responsible, but hopefully this information was useful.

**Comment by demolish50** [comment]
I've just seen it work intermittently for me. It did not work. I then decided to wipe the essentials xml and reconfigure everything, it then worked, one time. Then the next restart it stopped working.

**Comment by dodexahedron** [comment]
@Devlah, you need to update essentials to fix that particular error.

**Comment by dodexahedron** [comment]
@demolish50, do you have logs?
I'd like to see what it was doing.

**Comment by dodexahedron** [comment]
This may potentially be fixed by what I did for #9. Once that version is released, try that and let me know how it goes.

**Comment by eXactMatX** [comment]
Information (/info) work
greeting item/message not work
Safe Docking (/dock) not work

2015-03-31 23:17:55.9645|Info|SEModAPIExtensions.API.ChatManager.SendPrivateChatMessage|Chat - Server: Type /info followed by: motd for more info.  For example: '/info motd' to view MOTD.
2015-03-31 23:18:01.2395|Info|SEModAPIExtensions.API.ChatManager.SendPrivateChatMessage|Chat - Server: test
2015-03-31 23:18:06.1462|Info|SEModAPIExtensions.API.ChatManager.SendPrivateChatMessage|Chat - Server: Available subcommands for '/dock' command: validate, dock, undock, list
2015-03-31 23:18:15.0486|Info|SEModAPIExtensions.API.ChatManager.SendPrivateChatMessage|Chat - Server: Can not locate docking zone 'DockB'.  There must be 4 beacons with the name 'DockB' to create a docking zone.  Beacons must be fully built!

![2015-03-31_00001](https://cloud.githubusercontent.com/assets/9723877/6929642/c13e3542-d7fc-11e4-9d51-5142783b3650.jpg)

2015-03-31 23:15:51.2640|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 0 arguments ...
2015-03-31 23:15:51.3451|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished loading SandboxGameAssemblyWrapper
2015-03-31 23:15:51.4372|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|All main types passed reflection unit tests!
2015-03-31 23:15:51.4712|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|All entity types passed reflection unit tests!
2015-03-31 23:15:51.5263|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|All block types passed reflection unit tests!
2015-03-31 23:15:51.5283|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2015-03-31 23:15:51.5283|Info|SEModAPIInternal.API.Server.ServerAssemblyWrapper.get_Instance|Finished loading ServerAssemblyWrapper
2015-03-31 23:15:51.5283|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished loading PluginManager
2015-03-31 23:15:51.5283|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2015-03-31 23:15:51.5283|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2015-03-31 23:15:51.5593|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2015-03-31 23:15:51.5593|Info|SEServerExtender.Program.Start|Opening up WCF service listener
2015-03-31 23:16:06.6456|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Loading Session Settings
2015-03-31 23:16:09.4432|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|
Max Players: 25
2015-03-31 23:16:09.4432|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|OnlineMode: OFFLINE
2015-03-31 23:16:09.4432|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|GameMode: Creative
2015-03-31 23:16:09.4432|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Scenario: Asteroids
2015-03-31 23:16:09.4432|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|World Size: 0

2015-03-31 23:16:09.4973|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished loading PlayerManager
2015-03-31 23:16:09.4973|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished loading NetworkManager
2015-03-31 23:16:11.6323|Info|SEModAPIInternal.API.Common.PlayerMap.get_Instance|Finished loading PlayerMap
2015-03-31 23:16:47.2492|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Loading plugins ...
2015-03-31 23:16:47.2492|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Scanning: C:\ProgramData\SpaceEngineersDedicated\SpaceEngineers\Mods
2015-03-31 23:16:47.2492|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Finished loading plugins
2015-03-31 23:16:47.2622|Info|SEModAPIExtensions.API.PluginManager.Init|Initializing plugins ...
2015-03-31 23:16:47.2622|Info|SEModAPIExtensions.API.PluginManager.InitPlugin|Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\SpaceEngineers\Mods\Essentials\Essentials.dll - f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-03-31 23:16:48.3983|Info|SEModAPIExtensions.API.PluginManager.Init|Finished initializing plugins
2015-03-31 23:16:51.6323|Info|SEModAPIInternal.API.Common.FactionsManager.GetSubTypeEntity|Finished loading WorldManager
2015-03-31 23:20:03.9221|Info|SEModAPIExtensions.API.Server.StopServer|Stopping server
2015-03-31 23:20:03.9221|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.ExitGame|Exiting
2015-03-31 23:20:03.9221|Info|SEModAPIExtensions.API.PluginManager.UnloadPlugin|Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-03-31 23:20:04.1393|Info|System.Windows.Forms.Button.OnMouseUp|Server has been stopped
2015-03-31 23:20:04.4552|Info|SEModAPIExtensions.API.Server.RunServer|Server has stopped running

**Comment by Lordicon** [comment]
I have the greeting message, MOTD and waypoints not working for some people on my server but other people claim it is working. I myself see it sometimes when I login but other times it does not display or show up. Sorry no logs.

**Comment by dodexahedron** [comment]
The greetings are definitely working.  The problem with people not seeing them is just a consequence of how chat works, in the game.  If they take too long to get in, they'll simply miss the greeting message because it will age out and disappear.  Not really anything I can do about that.
I'm going to close this issue.
If something changes in the future such that I can influence how long chat messages hang around or something, I'll re-open it.
