### ISSUE TITLE
Missing Method Exception SEServerExtender v1.79.8.411 & Essentials 1.12.0.2392

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/EssentialsPlugin#30]
@dodexahedron As requested the bug posted in the correct tracker. Both SEServerExtender and Essentials are up-to-date.

2015-04-25 17:48:08.2655|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
at EssentialsPlugin.Essentials.<>c__DisplayClass3.b__2()
2015-04-25 17:48:18.2793|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
at EssentialsPlugin.Essentials.<>c__DisplayClass3.b__2()
2015-04-25 17:48:28.3915|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
at EssentialsPlugin.Essentials.<>c__DisplayClass3.b__2()
2015-04-25 17:48:38.4959|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
at EssentialsPlugin.Essentials.<>c__DisplayClass3.b__2()
2015-04-25 17:48:48.6045|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
at EssentialsPlugin.Essentials.<>c__DisplayClass3.b__2()
2015-04-25 17:49:00.5507|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
at EssentialsPlugin.Essentials.<>c__DisplayClass3.b__2()

It seems to be happening after the latest update of SEServerExtender

**Comment by dodexahedron** [comment]
Interesting.
Can you pastebin your Essentials-Settings.xml file?

**Comment by dodexahedron** [comment]
Also, update to 1.12.0.2399 and see if that fixes you.

**Comment by Ragnar24** [comment]
Going to continue post here since it is more relevant here. So I double checked the installation of both server extender and essentials and am still getting the same error. What I realized is that even though I downloaded the Essentials-v.1.12.2399, after installation it still shows that the files are 1.12.2392.

**Comment by tdmike** [comment]
As requested my xml file: http://pastebin.com/gT3BuXai. I just updated to the new version and the problems seem to be gone, I'll monitor for the day to see if it's stable now. If so I will close this issue for you. :)

**Comment by tdmike** [comment]
So I just stumbled on another issue, apparently the entire auto save function doesn't work properly. Last night I had a rollback of several hours. My setting is to auto save every ten minutes, and at 7am every night/morning the server is restarted. But it seems that the server does not save at all. Not even when I give it a save commando. I'm pretty sure this issue is not only part of Essentials, so should I open a new issue on the SEServerExtender tracker ?

**Comment by tdmike** [comment]
So since your last I had several crashes that didn't show up in the logs, I only know of them because people on my server told me so. After checking the logs I only see the server starting up multiple times, but no apparent reason for the crash or even a line about the crashes. I also am experiencing some issues regarding the update to the interface. Chat is not show on the server and I cant see items in inventory's (like storage container > items normally I could view the items there but since your last update this doesn't work anymore) from the entity tab.

**Comment by dodexahedron** [comment]
Are you on 417 or 411?

**Comment by tdmike** [comment]
Well now I was running on 411 when I had these problems, but now on 417 I get this nice looking screen:

![untitled](https://cloud.githubusercontent.com/assets/6142706/7353145/a59d2a58-ed11-11e4-8e20-d50a70851ecd.png)

If you need any logs please let me know

**Comment by dodexahedron** [comment]
This has been fixed in SESE version 1.79.08.419.
