### ISSUE TITLE
/admin delete inactive not work

### ISSUE THREAD

**Issue by SwApiy** [SEServerExtender/EssentialsPlugin#34]
/admin delete inactive  not work 

2015-05-01 17:04:18.0805|Info|ChatHandler Error: System.NullReferenceException:
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei EssentialsPlugin.ChatHandlers.AdminDelete.HandleAdminDeleteInactive.Handl
eCommand(UInt64 userId, String[] words)
   bei EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String mess
age)

**Comment by MescalineMonkey** [comment]
Same in my server. I can post the error message if you need it.

**Comment by dodexahedron** [comment]
Please do.
And can you also post your Essentials-Settings.xml file?

**Comment by SwApiy** [comment]
2015-05-09 17:08:45.9878|Info|Chat - Server: Scanning for grids with owners that
 haven't logged in 10 days.  (Must Have Login Info=False)
2015-05-09 17:08:46.2018|Info|ChatHandler Error: System.NullReferenceException:
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei EssentialsPlugin.ChatHandlers.HandleAdminScanInactive.HandleCommand(UInt6
4 userId, String[] words)
   bei EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String mess
age)

After Space Engineers update .....

**Comment by MescalineMonkey** [comment]
Info:ChatHandler Error: System.NullReferenceException: Object reference not set to an instance of an object.
at EssentialsPlugin.ChatHandlers.HandleAdminScanInactive.HandleCommand(UInt64 userId, String[] words)
at EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String message)
