### ISSUE TITLE
Essentials error with 1.085 and newest version of extender.

### ISSUE THREAD

**Issue by wweiland** [SEServerExtender/EssentialsPlugin#42]
2015-06-04 14:38:28.9978|Error|System.TypeLoadException: Could not load type 'Sa
ndbox.Common.ObjectBuilders.VRageData.SerializableVector3I' from assembly 'Sandb
ox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembl
y, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at SEModAPIExtensions.API.PluginManager.IsOldPlugin(Assembly assembly)
   at SEModAPIExtensions.API.PluginManager.LoadPlugins(Boolean forceLoad)
2015-06-04 14:38:29.0118|Info|Finished loading plugins
2015-06-04 14:38:29.0168|Info|Initializing plugins ...

When I go to plugins tab it is empty.

**Comment by wweiland** [comment]
Opps, sorry, just noticed the update.  Thanks!!
