### ISSUE TITLE
Essentials .2432 with extender .498 and space engineers 1.085 008

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/EssentialsPlugin#43]
2015-06-04 21:56:42.6448|Info|EssentialsPlugin.Essentials+<>c__DisplayClass3.<PluginProcessing>b__2|Handler Problems: 400 - SEModAPI.API.GameInstallationInfoException: Exception of type 'SEModAPI.API.GameInstallationInfoException' was thrown.
   at SEModAPIInternal.API.Entity.BaseObjectManager.LoadContentFile[T,TS](FileInfo fileInfo)
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridEntity..ctor(FileInfo prefabFile)
   at EssentialsPlugin.ProcessHandlers.ProcessCommunication.AddGlobalRelay()
   at EssentialsPlugin.ProcessHandlers.ProcessCommunication.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()

**Comment by xxam** [comment]
this is from essentials logfile

**Comment by xxam** [comment]
and this from extender logfile:

2015-06-04 21:56:42.6448|Error|SEModAPIInternal.API.Entity.BaseObjectManager.LoadContentFile|System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.TypeLoadException: Could not load type 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_CubeGrid' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1246_MyObjectBuilder_CubeGrid()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at SEModAPIInternal.API.Entity.BaseObjectManager.ReadSpaceEngineersFile[T,TS](String filename)
   at SEModAPIInternal.API.Entity.BaseObjectManager.LoadContentFile[T,TS](FileInfo fileInfo)

**Comment by dodexahedron** [comment]
This is due to changes in CubeGrids.
The content files need to be updated.
I'll fix that.
This doesn't break the game, at least.  Although it does break the player move mechanism and the commrelay functionality.

**Comment by dodexahedron** [comment]
The content files are updated and SESE's load and save methods have been updated to work with SE 1.85.
The fix will be posted for both SESE and Essentials shortly.
