### ISSUE TITLE
/admin scan inactive # no longer working

### ISSUE THREAD

**Issue by joemorin73** [SEServerExtender/EssentialsPlugin#45]
Using the command gives the following error:

2015-06-06 10:44:14.4075|Info|Chat - Server: Scanning for grids with owners that haven't logged in 8 days.  (Must Have Login Info=True)
2015-06-06 10:44:14.5995|Info|ChatHandler Error: System.NullReferenceException:Object reference not set to an instance of an object.
   at EssentialsPlugin.ChatHandlers.HandleAdminScanInactive.HandleCommand(UInt64 userId, String[] words)
   at EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String message)

**Comment by SilentSymphony** [comment]
Same error here in version 1.85.9.522, Was also happening with release 1.85.09.518
This error was not present for me in 1.85.09.517

**Comment by 88tom** [comment]
HI, i've currently the last release and i have the same problem.. can you fix this asap? it's a very important future..

**Comment by SilentSymphony** [comment]
This suddenly started working for me after the base game updated today.

**Comment by 88tom** [comment]
I've always the same problem, there is a way to fix all??
