### ISSUE TITLE
Selecting concealed entity in Entities Window causes NullReferenceException

### ISSUE THREAD

**Issue by Lordicon** [SEServerExtender/EssentialsPlugin#5]
On clicking a ship in the entities window the console is returning this error message in yellow text.

2015-03-28 16:44:54.4294|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7
eUEDKm='
2015-03-28 16:44:54.4294|Error|System.NullReferenceException: Object reference n
ot set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, S
tring fieldName)
2015-03-28 16:44:54.4294|Error|System.NullReferenceException: Object reference n
ot set to an instance of an object.
   at SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
2015-03-28 16:44:54.4294|Error|Failed to get entity method 'get_TotalRequiredInp
ut': Game entity was null
2015-03-28 16:44:54.4294|Error|System.Exception: Game entity was null
   at SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity,
String methodName)
2015-03-28 16:44:54.4294|Error|System.NullReferenceException: Object reference n
ot set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntit
y, String methodName, Object[] parameters, Type[] argTypes)
   at SEModAPIInternal.API.Common.PowerManager.get_AvailablePower()

**Comment by dodexahedron** [comment]
I can't duplicate this.
Any chance you could get a copy of your world to me?

**Comment by Lordicon** [comment]
I can not get you this copy right now but I will see about it in a bit, I noticed something that is happening. I am clicking the entities (Ships in game). This only happens to certain ships. Mainly the ones that I believe are being concealed with the concealed settings and not being released. I noticed that the ship in the list causing this issue has its xyz cords set to 0 0 0. I will try and get the files to you.

**Comment by zrisher** [comment]
I suggest this issue be renamed to "Selecting concealed entity in Entities Window causes NullReferenceException"

**Comment by DigTron** [comment]
Happening over here too, tried on several grids, only the concealed ones cause the error to post, and upon forcing them to reveal the error does not happen when selecting the same grids.

Selecting one concealed grid once causes the following errors to post.


		2015-04-23 14:24:44.1827|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7eUEDKm='
		2015-04-23 14:24:44.1827|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, String fieldName)
		2015-04-23 14:24:44.1827|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
		2015-04-23 14:24:44.1827|Error|Failed to get entity method 'get_TotalRequiredInput': Game entity was null
		2015-04-23 14:24:44.1827|Error|System.Exception: Game entity was null
		   at SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity,String methodName)
		2015-04-23 14:24:44.1827|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters, Type[] argTypes)
		   at SEModAPIInternal.API.Common.PowerManager.get_AvailablePower()
		2015-04-23 14:24:44.1957|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7eUEDKm='
		2015-04-23 14:24:44.1957|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, String fieldName)
		2015-04-23 14:24:44.1957|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
		2015-04-23 14:24:44.2227|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7eUEDKm='
		2015-04-23 14:24:44.2227|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, String fieldName)
		2015-04-23 14:24:44.2227|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
		2015-04-23 14:24:44.2227|Error|Failed to get entity method 'get_TotalRequiredInput': Game entity was null
		2015-04-23 14:24:44.2227|Error|System.Exception: Game entity was null
		   at SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity,String methodName)
		2015-04-23 14:24:44.2227|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters, Type[] argTypes)
		   at SEModAPIInternal.API.Common.PowerManager.get_AvailablePower()
		2015-04-23 14:24:44.2227|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7eUEDKm='
		2015-04-23 14:24:44.2227|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, String fieldName)
		2015-04-23 14:24:44.2227|Error|System.NullReferenceException: Object reference not set to an instance of an object.
		   at SEModAPIInternal.API.Common.PowerManager.get_TotalPower()

**Comment by dodexahedron** [comment]
Does this still happen?
I seem to remember putting code in that keeps concealed entities from showing up in the first place, a while back, but I could be imagining that.
