### ISSUE TITLE
Extender .527 Essentials 1.13.2.2441 Error messages in logfiles concerning entitymanagement 

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/EssentialsPlugin#50]
I guess its related to entity mangement / Concealment: im getting a lot of the following errors:

2015-06-12 21:17:09.3431|Error|EssentialsPlugin.EntityManagers.EntityManagement.CheckAndRevealEntities|System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Sandbox.ModAPI.MyEntitiesHelper_ModAPI.Sandbox.ModAPI.IMyEntities.GetEntities(HashSet`1 entities, Func`2 collect)
   at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndRevealEntities()
2015-06-12 21:17:36.0801|Error|EssentialsPlugin.EntityManagers.EntityManagement.CheckAndRevealEntities|System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Sandbox.ModAPI.MyEntitiesHelper_ModAPI.Sandbox.ModAPI.IMyEntities.GetEntities(HashSet`1 entities, Func`2 collect)
   at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndRevealEntities()
2015-06-12 21:17:36.7061|Error|EssentialsPlugin.ProcessHandlers.ProcessCommunication.Handle|ProcessCommunication: Problem getting entities, skipping update
2015-06-12 21:17:58.6441|Error|EssentialsPlugin.ProcessHandlers.ProcessCommunication.Handle|ProcessCommunication: Problem getting entities, skipping update
2015-06-12 21:18:24.7241|Error|EssentialsPlugin.EntityManagers.EntityManagement.CheckAndConcealEntities|Error getting entity list, skipping check
    |System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Sandbox.ModAPI.MyEntitiesHelper_ModAPI.Sandbox.ModAPI.IMyEntities.GetEntities(HashSet`1 entities, Func`2 collect)
   at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndConcealEntities()

**Comment by xxam** [comment]
today while the error appeared somebody saw the culprit on the server.

A ship was jumping "out of the grid" at the moment this error message occured:
2015-06-16 17:44:09.1194|Error|EssentialsPlugin.ProcessHandlers.ProcessCommunication.Handle|ProcessCommunication: Problem getting entities, skipping update

**Comment by Tyrsis** [comment]
This is an ignorable error.  It just means when it went to check to conceal, the main thread modified the ship hashset, invalidating it, meaning that it could not run.  It's not really an error, more like info.

**Comment by dodexahedron** [comment]
It really probably ought to be logged at trace level, since it's generally not necessary to care that it happened.
