### ISSUE TITLE
There seems to be an issue with CubeGrids and the Dock/Undock process in Essentials

### ISSUE THREAD

**Issue by markam67** [SEServerExtender/EssentialsPlugin#51]
The Sever Extender while running Essentials plugin will allow you to create a dock area and report it properly, it will also allow you to dock a small ship and remove it from the world. The problem is that when attempting to undock the ship you get the following error;

2015-06-15 07:42:06.4912|Info|EssentialsPlugin.Essentials.HandleChatMessage|ChatHandler Error: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.TypeLoadException: Could not load type 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_CubeGrid' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1246_MyObjectBuilder_CubeGrid()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at SEModAPIInternal.API.Entity.BaseObjectManager.ReadSpaceEngineersFile[T,TS](String filename)
   at EssentialsPlugin.ChatHandlers.Dock.HandleDockUndock.HandleCommand(UInt64 userId, String[] words)
   at EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String message)

I also found this error in the essentials log:
Load(): System.IO.FileNotFoundException: Unable to find the specified file.
   at Sandbox.ModAPI.MyAPIUtilities.Sandbox.ModAPI.IMyUtilities.ReadFileInLocalStorage(String file, Type callingType)
   at DedicatedEssentials.Settings.Load()

Hope this all helps.

Archmage

**Comment by dodexahedron** [comment]
This is probably due to a change in saving made a while ago.
I'll take a look at this.

**Comment by markam67** [comment]
Dode,

Did the latest Extender update fix this issue? I noted that you stated that it fixed export issues with cubegrids. Also if it did address that issues are ships exported previously now dead? non retrievable?

Thanks,

Archmage
