### ISSUE TITLE
[BUG] Undock feature having an issue.

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/EssentialsPlugin#62]
/dock undock a
2015-07-03 22:20:51.3913|Info|EssentialsPlugin.Essentials.HandleChatMessage|ChatHandler Error: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.TypeLoadException: Could not load type 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_CubeGrid' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1246_MyObjectBuilder_CubeGrid()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at SEModAPIInternal.API.Entity.BaseObjectManager.ReadSpaceEngineersFile[T,TS](String filename)
   at EssentialsPlugin.ChatHandlers.Dock.HandleDockUndock.HandleCommand(UInt64 userId, String[] words)
   at EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String message)

**Comment by dodexahedron** [comment]
This issue should be resolved in version 2452.
