### ISSUE TITLE
[v1.13.3.2452-alpha] Failed to get static method 'SendEntityCreated'

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/EssentialsPlugin#68]
Getting this right after session loading with latest build of SE...
Doesn't seem a major issue as game still runs regardless.

2015-08-08 01:17:09.4432|Info|SEModAPIExtensions.API.PluginManager.Init|Finished initializing plugins
2015-08-08 01:17:09.9362|Error|SEModAPIInternal.API.Entity.BaseObject.GetStaticMethod|Failed to get static method 'SendEntityCreated'
2015-08-08 01:17:09.9362|Error|SEModAPIInternal.API.Entity.BaseObject.GetStaticMethod|System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at SEModAPIInternal.API.Entity.BaseObject.GetStaticMethod(Type objectType, String methodName)
2015-08-08 01:17:09.9362|Error|SEModAPIInternal.API.Entity.BaseObject.InvokeStaticMethod|Failed to invoke static method 'SendEntityCreated': Method is empty
2015-08-08 01:17:09.9362|Error|SEModAPIInternal.API.Entity.BaseObject.InvokeStaticMethod|System.Exception: Method is empty
   at SEModAPIInternal.API.Entity.BaseObject.InvokeStaticMethod(Type objectType, String methodName, Object[] parameters)

**Comment by dodexahedron** [comment]
This should be a relatively easy fix. I won't be home tonight to fix it, though.

-----Original Message-----

**Comment by niapet** [comment]
Would this error cause mod to fail to display to players?
