### ISSUE TITLE
Exception from Conceal

### ISSUE THREAD

**Issue by TheEngineer50** [SEServerExtender/EssentialsPlugin#86]
Have you seen this before? Obviously something with connectors.  I think it's the same grid every time. I'll let ya know what I figure out.

016-04-09 07:55:43.8203|Error|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.Cube.MyShipConnector.RemoveConstraint(MyShipConnector otherConnector, HkConstraint constraint)
   at Sandbox.Game.Entities.Cube.MyShipConnector.CubeGrid_OnPhysicsChanged(MyEntity obj)
   at System.Action`1.Invoke(T obj)
   at VRage.Game.Entity.MyEntity.RaisePhysicsChanged()
   at VRage.Game.Entity.MyEntity.Delete()
   at Sandbox.Game.Entities.MyEntities.DeleteRememberedEntities()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   --- End of inner exception stack trace ---

**Comment by rexxar-tc** [comment]
This has been taken care of by the rewrite. Should be released in a few weeks.
