### ISSUE TITLE
[v1.13.6.1-alpha] Utility Grids List not working

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/EssentialsPlugin#88]
Not a big issue that has to be solved immediatley as I can locate grids for players when i'm available. Was picked up just a short while ago by a player trying to use the command.

2016-04-15 23:41:52.9428|Info|Chat - Client 'MAB': /utility grids list
2016-04-15 23:41:53.0238|Info|ChatHandler Error: System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyCubeBlock' to type 'Sandbox.Game.Entities.Cube.MyTerminalBlock'.
   at EssentialsPlugin.Utility.CubeGrids.IsFullOwner(MyCubeGrid grid, Int64 ownerId, IMyPlayer factionPlayer)
   at EssentialsPlugin.ChatHandlers.HandleUtilityGridsList.HandleCommand(UInt64 userId, String[] words)
   at EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String message)

Great work on the latest versions of SESE and Essentials, it has been great to be able to use the entities TAB again.

**Comment by rexxar-tc** [comment]
Ah, I missed that one. It'll be fixed next release.
