### ISSUE TITLE
old settings file crashes server

### ISSUE THREAD

**Issue by Tostito** [SEServerExtender/EssentialsPlugin#96]
just more of an FYI and I am trying to narrow down to what exactly is causing it. however deleting the old settings file does make the crash go away. 

server logs -

2016-06-04 17:44:51.544 - Thread:   5 ->  Loading voxel storage from file 'F:\DedicatedServer\Content\VoxelMaps\MediumStoneIronCoreStoneCoverage.vx2'
2016-06-04 17:44:51.545 - Thread:   5 ->  Loading voxel storage from file 'F:\DedicatedServer\Content\VoxelMaps\MediumStoneIronCoreStoneCoverage.vx2'
2016-06-04 17:44:57.149 - Thread:   5 ->  GC Memory: 2,209,830,440 B
2016-06-04 17:44:58.407 - Thread:   5 ->  Loading voxel storage from file 'F:\DedicatedServer\Content\VoxelMaps\MediumStoneIronCoreStoneCoverage.vx2'
2016-06-04 17:44:58.632 - Thread:   5 ->  Loading voxel storage from file 'F:\DedicatedServer\Content\VoxelMaps\MediumStoneIronCoreStoneCoverage.vx2'
2016-06-04 17:44:58.813 - Thread:   5 ->  Game ready... Press Ctrl+C to exit
2016-06-04 17:47:10.159 - Thread:   5 ->  Exiting..
2016-06-04 17:47:10.161 - Thread:   5 ->  MySession::Unload START
2016-06-04 17:47:10.162 - Thread:   5 ->  AutoSaveInMinutes: 0
2016-06-04 17:47:10.162 - Thread:   5 ->  MySandboxGame.IsDedicated: True
2016-06-04 17:47:10.162 - Thread:   5 ->  IsServer: True
2016-06-04 17:47:12.686 - Thread:   5 ->  MySunWind.UnloadData - START
2016-06-04 17:47:12.686 - Thread:   5 ->  MySunWind.UnloadData - END
2016-06-04 17:47:12.687 - Thread:   5 ->  Unloading Procedural World Generator
2016-06-04 17:47:12.704 - Thread:   7 ->  External debugger: interrupted.
2016-06-04 17:47:12.706 - Thread:   5 ->  Network readers disposed
2016-06-04 17:47:12.909 - Thread:   5 ->  Network readers disposed
2016-06-04 17:47:12.909 - Thread:   5 ->  Logging off Steam...
2016-06-04 17:47:12.909 - Thread:   5 ->  Shutting down server...
2016-06-04 17:47:12.972 - Thread:   5 ->  Done
2016-06-04 17:47:12.972 - Thread:   5 ->  MyDefinitionManager.PreloadDefinitions() - START
2016-06-04 17:47:12.972 - Thread:   5 ->  MyDefinitionManager.PreloadDefinitions() - END
2016-06-04 17:47:13.659 - Thread:   5 ->  MySession::Unload END
2016-06-04 17:47:13.659 - Thread:   5 ->  MySandboxGame.UnloadData() - START
2016-06-04 17:47:13.659 - Thread:   5 ->  MySandboxGame.UnloadData() - END

or -

2016-06-04 18:02:44.308 - Thread:   5 ->  Game ready... Press Ctrl+C to exit
2016-06-04 18:02:50.741 - Thread:  30 ->  Exception occured: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at hkpConvexVerticesShape.new(UInt64 )
   at Havok.HkConvexVerticesShape.initShape(Vector3[] verts, Int32 count, Boolean shrink, Single convexRadius)
   at Sandbox.Game.Components.MyUseObjectsComponent.RecreatePhysics()
   at Sandbox.Game.Components.MyUseObjectsComponent.LoadDetectorsFromModel()
   at Sandbox.Game.Entities.MyCubeBlock.Init()
   at Sandbox.Game.Entities.MyCubeBlock.Init(MyObjectBuilder_CubeBlock builder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.MyShipController.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.MyCockpit.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MySlimBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid, MyCubeBlock fatBlock)
   at Sandbox.Game.Entities.MyCubeGrid.AddCubeBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge, MyCubeBlockDefinition blockDefinition)
   at Sandbox.Game.Entities.MyCubeGrid.AddBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge)
   at Sandbox.Game.Entities.MyCubeGrid.InitInternal(MyObjectBuilder_EntityBase objectBuilder, Boolean rebuildGrid)
   at Sandbox.Game.Entities.MyEntities.InitEntity(MyObjectBuilder_EntityBase objectBuilder, MyEntity& entity)
   at Sandbox.ModAPI.MyEntitiesHelper_ModAPI.VRage.ModAPI.IMyEntities.CreateFromObjectBuilder(MyObjectBuilder_EntityBase objectBuilder)
   at EssentialsPlugin.EntityManagers.EntityManagement.RevealEntityObsolete(KeyValuePair`2 item)
   at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndRevealEntitiesObsolete()
   at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndRevealEntities()
   at EssentialsPlugin.ProcessHandlers.ProcessConceal.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass223_0.<PluginProcessing>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2016-06-04 18:02:50.742 - Thread:  30 ->  Hiding window
2016-06-04 18:02:50.947 - Thread:  30 ->  Network readers disposed
2016-06-04 18:02:50.949 - Thread:  30 ->  Logging off Steam...
2016-06-04 18:02:50.949 - Thread:  30 ->  Shutting down server...
2016-06-04 18:02:50.991 - Thread:  30 ->  Done
2016-06-04 18:02:50.992 - Thread:  30 ->  Hiding window done
2016-06-04 18:02:50.992 - Thread:  30 ->  Showing message
2016-06-04 18:02:50.995 - Thread:  30 ->  ERROR: branch name cannot be resolved, services=
2016-06-04 18:02:50.995 - Thread:  30 ->  ERROR: branch name cannot be resolved, services=
2016-06-04 18:02:50.995 - Thread:  30 ->  ERROR: branch name cannot be resolved, services=

**Comment by Tostito** [comment]
update. switching on dynamic conceal causes SESE to crash. 

info - test world uses only the newessentials steamworkshop mod.

**Comment by Tostito** [comment]
I have tried re downloading the server but unfortunately this issue persists.

i seem to be catching the log after the server crashes and tries to restart. updated the log above.

**Comment by Tostito** [comment]
might have found a fix ..

**Comment by rexxar-tc** [comment]
When the world starts, Essentials tries to reveal any grids that were concealed using the old system. It's crashing now because some stuff is not happening in the game thread when it should be. This will be fixed shortly.

**Comment by rexxar-tc** [comment]
Latest release fixes this.
