### ISSUE TITLE
New strange crash

### ISSUE THREAD

**Issue by foogs** [SEServerExtender/EssentialsPlugin#97]
during the battle time, I copied and pasted a small ship (fighter) and the server crash.

```
2016-06-05 03:05:33.9240|Error|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.MyCubeGrid.OnChangeOwnerRequest(Int64 blockId, Int64 owner, MyOwnershipShareModeEnum shareMode)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Single unreliablePriority, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5](T1 arg1, T5 arg5, Func`2 action, T2 arg2, T3 arg3, T4 arg4, EndpointId endpointId, Single unreliablePriority)
   at Sandbox.Game.Entities.MyCubeGrid.ChangeOwnerRequest(MyCubeGrid grid, MyCubeBlock block, Int64 playerId, MyOwnershipShareModeEnum shareMode)
   at Sandbox.Game.Entities.MyCubeBlock.ChangeBlockOwnerRequest(Int64 playerId, MyOwnershipShareModeEnum shareMode)
   at EssentialsPlugin.Utility.PlayerBlockEnforcement.<>c__DisplayClass6_0.<ChangeOwnershipToNearestPlayer>b__0()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClass54_1.<GameAction>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
    |System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.MyCubeGrid.OnChangeOwnerRequest(Int64 blockId, Int64 owner, MyOwnershipShareModeEnum shareMode)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Single unreliablePriority, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5](T1 arg1, T5 arg5, Func`2 action, T2 arg2, T3 arg3, T4 arg4, EndpointId endpointId, Single unreliablePriority)
   at Sandbox.Game.Entities.MyCubeGrid.ChangeOwnerRequest(MyCubeGrid grid, MyCubeBlock block, Int64 playerId, MyOwnershipShareModeEnum shareMode)
   at Sandbox.Game.Entities.MyCubeBlock.ChangeBlockOwnerRequest(Int64 playerId, MyOwnershipShareModeEnum shareMode)
   at EssentialsPlugin.Utility.PlayerBlockEnforcement.<>c__DisplayClass6_0.<ChangeOwnershipToNearestPlayer>b__0()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClass54_1.<GameAction>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
Object reference not set to an instance of an object. System.NullReferenceException Void OnChangeOwnerRequest(Int64, Int64, VRage.Game.MyOwnershipShareModeEnum)    at Sandbox.Game.Entities.MyCubeGrid.OnChangeOwnerRequest(Int64 blockId, Int64 owner, MyOwnershipShareModeEnum shareMode)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Single unreliablePriority, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5](T1 arg1, T5 arg5, Func`2 action, T2 arg2, T3 arg3, T4 arg4, EndpointId endpointId, Single unreliablePriority)
   at Sandbox.Game.Entities.MyCubeGrid.ChangeOwnerRequest(MyCubeGrid grid, MyCubeBlock block, Int64 playerId, MyOwnershipShareModeEnum shareMode)
   at Sandbox.Game.Entities.MyCubeBlock.ChangeBlockOwnerRequest(Int64 playerId, MyOwnershipShareModeEnum shareMode)
   at EssentialsPlugin.Utility.PlayerBlockEnforcement.<>c__DisplayClass6_0.<ChangeOwnershipToNearestPlayer>b__0()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClass54_1.<GameAction>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
2016-06-05 03:05:33.9709|Info|SEModAPIExtensions.API.Server.RunServer|Server has stopped running

```
[logs.zip](https://github.com/SEServerExtender/EssentialsPlugin/files/299118/logs.zip)

**Comment by foogs** [comment]
Another crash again during the battle, entered the command / admin stop all, and crush the server
All logs on zip.
```
2016-06-05 12:41:45.7571|Error|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at EssentialsPlugin.ChatHandlers.HandleAdminStop.<>c__DisplayClass7_0.<Stop>b__0()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClass54_1.<GameAction>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
    |System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at EssentialsPlugin.ChatHandlers.HandleAdminStop.<>c__DisplayClass7_0.<Stop>b__0()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClass54_1.<GameAction>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
Object reference not set to an instance of an object. System.NullReferenceException Void <Stop>b__0()    at EssentialsPlugin.ChatHandlers.HandleAdminStop.<>c__DisplayClass7_0.<Stop>b__0()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClass54_1.<GameAction>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
2016-06-05 12:41:45.80
40|Info|SEModAPIExtensions.API.Server.RunServer|Server has stopped running
```

[logs.zip](https://github.com/SEServerExtender/EssentialsPlugin/files/299275/logs.zip)

**Comment by foogs** [comment]
Another crash (
```
2016-06-05 13:37:46.4708|Error|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction|System.Threading.ThreadAbortException: Поток находился в процессе прерывания.
   в System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   в System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   в System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   в SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action action)
    |System.Threading.ThreadAbortException: Поток находился в процессе прерывания.
   в System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   в System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   в System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   в SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action action)
```
[logs.zip](https://github.com/SEServerExtender/EssentialsPlugin/files/299297/logs.zip)

**Comment by foogs** [comment]
= _ = Last update unplayable = / crash every hour and sim speed drops. I rolled back to old version concealment tools

**Comment by foogs** [comment]
v1.134.06.179-alpha version works good, sim speed not drop , conceal works fine =)

**Comment by rexxar-tc** [comment]
I got a stream of emails notifying me that you've posted something every ten minutes for an hour. This is _beyond_ unnecessary. Of your last three comments here, one is entirely unrelated to this problem, and the other two are basically the same.

I'm going to lock this issue and the other issues you've posted today until I have a chance to investigate them.
